import 'element-plus/es/components/base/style';
import 'element-plus/theme-chalk/src/table.scss';
import 'element-plus/es/components/button/style';
import 'element-plus/es/components/checkbox/style';
import 'element-plus/es/components/icon/style';
import 'element-plus/es/components/tooltip/style';
import 'element-plus/es/components/scrollbar/style';
import 'element-plus/es/components/input/style';
import 'element-plus/es/components/select/style';
