import type { InputSelectValue } from './input-select';
declare const _default: import("vue").DefineComponent<{
    readonly layout: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => ["input", "select"] | ["select", "select"] | ["select", "input"] | ["input", "input"]) | (() => import("./input-select").InputSelectLayout) | ((new (...args: any[]) => ["input", "select"] | ["select", "select"] | ["select", "input"] | ["input", "input"]) | (() => import("./input-select").InputSelectLayout))[], unknown, import("./input-select").InputSelectLayout, () => import("./input-select").InputSelectLayout, boolean>;
    readonly leftValue: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue) | ((new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue))[], unknown, unknown, undefined, boolean>;
    readonly rightValue: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue) | ((new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue))[], unknown, unknown, undefined, boolean>;
    readonly leftProps: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps) | ((new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps))[], unknown, unknown, () => {}, boolean>;
    readonly rightProps: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps) | ((new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps))[], unknown, unknown, () => {}, boolean>;
}, () => import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
    [key: string]: any;
}>, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
    'update:leftValue': (_value: InputSelectValue) => boolean;
    'update:rightValue': (_value: InputSelectValue) => boolean;
    'left-change': (_value: InputSelectValue) => boolean;
    'right-change': (_value: InputSelectValue) => boolean;
    'left-focus': (event: FocusEvent) => boolean;
    'right-focus': (event: FocusEvent) => boolean;
    'left-blur': (event: FocusEvent) => boolean;
    'right-blur': (event: FocusEvent) => boolean;
    'left-clear': () => boolean;
    'right-clear': () => boolean;
    'left-visible-change': (visible: boolean) => boolean;
    'right-visible-change': (visible: boolean) => boolean;
}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
    readonly layout: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => ["input", "select"] | ["select", "select"] | ["select", "input"] | ["input", "input"]) | (() => import("./input-select").InputSelectLayout) | ((new (...args: any[]) => ["input", "select"] | ["select", "select"] | ["select", "input"] | ["input", "input"]) | (() => import("./input-select").InputSelectLayout))[], unknown, import("./input-select").InputSelectLayout, () => import("./input-select").InputSelectLayout, boolean>;
    readonly leftValue: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue) | ((new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue))[], unknown, unknown, undefined, boolean>;
    readonly rightValue: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue) | ((new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue))[], unknown, unknown, undefined, boolean>;
    readonly leftProps: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps) | ((new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps))[], unknown, unknown, () => {}, boolean>;
    readonly rightProps: import("element-plus/es/utils").EpPropFinalized<(new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps) | ((new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps))[], unknown, unknown, () => {}, boolean>;
}>> & {
    "onUpdate:leftValue"?: ((_value: InputSelectValue) => any) | undefined;
    "onUpdate:rightValue"?: ((_value: InputSelectValue) => any) | undefined;
    "onLeft-change"?: ((_value: InputSelectValue) => any) | undefined;
    "onRight-change"?: ((_value: InputSelectValue) => any) | undefined;
    "onLeft-focus"?: ((event: FocusEvent) => any) | undefined;
    "onRight-focus"?: ((event: FocusEvent) => any) | undefined;
    "onLeft-blur"?: ((event: FocusEvent) => any) | undefined;
    "onRight-blur"?: ((event: FocusEvent) => any) | undefined;
    "onLeft-clear"?: (() => any) | undefined;
    "onRight-clear"?: (() => any) | undefined;
    "onLeft-visible-change"?: ((visible: boolean) => any) | undefined;
    "onRight-visible-change"?: ((visible: boolean) => any) | undefined;
}, {
    readonly layout: import("element-plus/es/utils").EpPropMergeType<(new (...args: any[]) => ["input", "select"] | ["select", "select"] | ["select", "input"] | ["input", "input"]) | (() => import("./input-select").InputSelectLayout) | ((new (...args: any[]) => ["input", "select"] | ["select", "select"] | ["select", "input"] | ["input", "input"]) | (() => import("./input-select").InputSelectLayout))[], unknown, import("./input-select").InputSelectLayout>;
    readonly leftValue: import("element-plus/es/utils").EpPropMergeType<(new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue) | ((new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue))[], unknown, unknown>;
    readonly rightValue: import("element-plus/es/utils").EpPropMergeType<(new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue) | ((new (...args: any[]) => string | number | boolean | Record<string, any> | import("element-plus/es/utils").EpPropMergeType<(ObjectConstructor | BooleanConstructor | NumberConstructor | StringConstructor)[], unknown, unknown>[]) | (() => InputSelectValue))[], unknown, unknown>;
    readonly leftProps: import("element-plus/es/utils").EpPropMergeType<(new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps) | ((new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps))[], unknown, unknown>;
    readonly rightProps: import("element-plus/es/utils").EpPropMergeType<(new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps) | ((new (...args: any[]) => Partial<Omit<import("element-plus/es/components/input").InputPropsPublic, "modelValue">> | Partial<Omit<import("element-plus/es/components/select").SelectPropsPublic, "modelValue">>) | (() => import("./input-select").InputSelectControlProps))[], unknown, unknown>;
}>;
export default _default;
